### ISSUE TITLE
curl under docker for mac breaks with "sslv3 alert handshake failure"; works fine under linux

### ISSUE THREAD

**Issue by MassimilianoLattanzio** [mailup/rest-samples-php#3]
Hi,
I've a problem with curl command to "https://services.mailup.com" under docker for mac, it fails with "sslv3 alert handshake failure" error. Investigating I found an issue related to this problem (https://github.com/docker/for-mac/issues/1136).

The only way I found to solve this issue is to add this line of code:
```
curl_setopt($curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_1);
```
in all methods that uses curl.

I don't know if this is the best way to correct the problem but maybe this can help others that are facing the same issue.

**Comment by p365labs** [comment]
@MassimilianoLattanzio 
it looks like the problem is on the backend side not allowing TCP segmentation, on Linux the MTU is set at 1500bytes by default, on OSX since 10.6 is set at **512bytes**. Increasing on OSX the MTU solves the problem, the server (https://services.mailup.com) don't reject the answers.

increasing the MTU like this :

```sudo sysctl net.inet.tcp.mssdflt=1024```

solves the problem.

**Comment by MassimilianoLattanzio** [comment]
Thanks @p365labs, problem solved 😃
